# Generated by Django 5.0 on 2025-09-26 23:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_petition_petitionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
